---
title: "Homework 8"
author: "Brianna Green"
date: "11/4/2020"
output: html_document
---

```{r}
library(tidyverse)
my_list<-list(a_data_frame=mtcars,
              another_data_frame=diamonds,
              a_vector=letters,
              another_vector=seq(from=4, to=9068, by=17),
              a_random_vector=rnorm(n=50, mean=10,sd=1))
```
Below is the names of the list elements
```{r}
names(my_list)
```
To get a hold of the elements by their name
```{r}
my_list[["a_vector"]]
my_list$a_vector

diamonds$aspect.ratio<-diamonds$x/diamonds$y
```
To access the elements by number
```{r}
my_list[[1]]
my_list[[1]][[3]]
my_list$a_data_frame$mpg
```
The code below shows how to get the elements of a data frame.
```{r}
mtcars["Valiant", "disp"]
mtcars[1:10,]
mtcars[1:10,"hp"]
mtcars[1:10,c("disp","hp","cyl")]
mtcars %>%
  select(disp,hp,cyl)
rows.more.than.5.cyl<-mtcars$cyl>5
mtcars[rows.more.than.5.cyl,"disp"]
hist(big.displacements)
mtcars[mtcars$cyl>5,]
mtcars[(mtcars$cyl>5 & mtcars$cyl<7) | mtcars$disp>300,]
```
Now, we use the lists.
```{r}
my_mod <- lm(qsec~hp,data=mtcars)
summary(my_mod)
my_mod
```
